steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env.local
      - --location=global
      - --keyring=form-builder
      - --key=cloudbuild-env
  # Install
  - name: "gcr.io/cloud-builders/yarn"
    args: ["install", "--ignore-engines"]
  # Test
  # - name: 'gcr.io/cloud-builders/yarn'
  #   args: ['test']
  # Build
  - name: "gcr.io/cloud-builders/yarn"
    args: ["build"]
  # Deploy
  - name: "gcr.io/cloud-builders/yarn"
    args: ["deploy:ci"]
