steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env.local
      - --location=global
      - --keyring=form-builder
      - --key=cloudbuild-env
  # Install
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  # Test
  # - name: 'gcr.io/cloud-builders/yarn'
  #   args: ['test']
  # Build
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
  # Deploy
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "deploy:ci"]
